### PR TITLE
Support for protocol type while creating client.

### PR DESCRIPTION
**Pull request by heychirag**
Added support for specifying protocol type while calling client().

### CODE REVIEW

**Comment by dims** [comment]
LGTM. thanks for the patch @heychirag

**Comment by lingxiankong** [comment]
hi @dims, I'm wondering when we could make a release to include this change?

**Comment by dims** [comment]
@lingxiankong i can cut one tomorrow

**Comment by dims** [comment]
@lingxiankong Done! sorry for the delay

**Pull request merged**
